version: '3.1'

services:

  recepten:
    #build:
    #  context: .
    #  dockerfile: /home/ubuntu/projects/recepten/Dockerfile
    image: rbontekoe/i_recepten
    ports:
      - "8100:8000"
    volumes:
      - recepten_data:/mnt/share_fs/Recepten
    command: bash /start.sh
    deploy:
      mode: replicated
      replicas: 3

volumes:
  recepten_data:
