version: '3.1'

services:

  recepten:
    #build:
    #  context: .
    #  dockerfile: /home/ubuntu/projects/recepten/Dockerfile
    image: 192.168.2.11:5000/recepten/i_recepten:v1.4.9
    ports:
      - "8100:8000"
    volumes:
      - recepten_data:/mnt/share_fs/Recepten
    command: bash /start.sh
    deploy:
      mode: replicated
      replicas: 2

volumes:
  recepten_data:
