apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: recepten
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recepten
  name: recepten-deploy
  namespace: recepten
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-sshd
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test-sshd
    spec:
      containers:
      - name: recepten-pod
        image: localhost:32000/i_recepten:v1.3.26
        ports:
        - containerPort: 8000
          name: test-sshd-http
---
apiVersion: v1
kind: Service
- Tessa Kiros

metadata:
  name: recepten-service
  namespace: recepten
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      nodePort: 30081
      targetPort: test-sshd-http
  selector:
    app: test-sshd
